// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yarqua.Infrastructure.Persistence;

#nullable disable

namespace Yarqua.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(YarquaDbContext))]
    partial class YarquaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("YarqtbRol", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("YarqtbRolClaim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("YarqtbUsuarioClaim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("YarqtbUsuarioLogin", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("YarqtbUsuarioRol", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("YarqtbUsuarioToken", (string)null);
                });

            modelBuilder.Entity("Yarqua.Domain.Entities.YarqtbCiudad", b =>
                {
                    b.Property<int>("CiuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Ciu_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CiuId"));

                    b.Property<string>("CiuCod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Ciu_Cod");

                    b.Property<string>("CiuNombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Ciu_Nombre");

                    b.Property<int>("DepoId")
                        .HasColumnType("int")
                        .HasColumnName("Depo_Id");

                    b.HasKey("CiuId");

                    b.HasIndex("DepoId", "CiuCod")
                        .IsUnique();

                    b.ToTable("YarqtbCiudad", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Yarqua.Domain.Entities.YarqtbCultivo", b =>
                {
                    b.Property<int>("CultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Cult_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CultId"));

                    b.Property<bool>("CultActivo")
                        .HasColumnType("bit")
                        .HasColumnName("Cult_Activo");

                    b.Property<decimal>("CultCapacidadCampo")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("Cult_CapacidadCampo");

                    b.Property<decimal>("CultDecisionRiego")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("Cult_DecisionRiego");

                    b.Property<DateTime>("CultFechaActualizacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("Cult_FechaActualizacion");

                    b.Property<DateTime>("CultFechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("Cult_FechaCreacion");

                    b.Property<string>("CultNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Cult_Nombre");

                    b.Property<decimal>("CultPorcentajeMaximo")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("Cult_PorcentajeMaximo");

                    b.HasKey("CultId");

                    b.HasIndex("CultNombre")
                        .IsUnique();

                    b.ToTable("YarqtbCultivo", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Yarqua.Domain.Entities.YarqtbDepartamento", b =>
                {
                    b.Property<int>("DepoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Depo_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepoId"));

                    b.Property<string>("DepoCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Depo_Code");

                    b.Property<string>("DepoNombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Depo_Nombre");

                    b.Property<int>("PaisId")
                        .HasColumnType("int")
                        .HasColumnName("Pais_Id");

                    b.HasKey("DepoId");

                    b.HasIndex("PaisId", "DepoCode")
                        .IsUnique();

                    b.ToTable("YarqtbDepartamento", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Yarqua.Domain.Entities.YarqtbDevicePushToken", b =>
                {
                    b.Property<long>("DptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Dpt_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DptId"));

                    b.Property<bool>("DptActivo")
                        .HasColumnType("bit")
                        .HasColumnName("Dpt_Activo");

                    b.Property<DateTime>("DptFechaActualizacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("Dpt_FechaActualizacion");

                    b.Property<DateTime>("DptFechaRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("Dpt_FechaRegistro");

                    b.Property<string>("DptPlatform")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("Dpt_Platform");

                    b.Property<string>("DptPushToken")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("Dpt_PushToken");

                    b.Property<string>("UsuaId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("Usua_Id");

                    b.HasKey("DptId");

                    b.HasIndex("DptPushToken")
                        .IsUnique();

                    b.ToTable("YarqtbDevicePushToken", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Yarqua.Domain.Entities.YarqtbEventoUsuario", b =>
                {
                    b.Property<long>("EvenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Even_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EvenId"));

                    b.Property<string>("EvenEvento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Even_Evento");

                    b.Property<DateOnly>("EvenFecha")
                        .HasColumnType("date")
                        .HasColumnName("Even_Fecha");

                    b.Property<DateTime>("EvenFechaActualizacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("Even_FechaActualizacion");

                    b.Property<DateTime>("EvenFechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("Even_FechaCreacion");

                    b.Property<TimeOnly>("EvenHora")
                        .HasColumnType("time")
                        .HasColumnName("Even_Hora");

                    b.Property<string>("EvenSensorId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Even_SensorId");

                    b.Property<string>("UsuaNombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Usua_Nombre");

                    b.HasKey("EvenId");

                    b.ToTable("YarqtbEventoUsuario", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Yarqua.Domain.Entities.YarqtbGrupo", b =>
                {
                    b.Property<int>("GrupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Grup_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GrupId"));

                    b.Property<bool>("GrupActivo")
                        .HasColumnType("bit")
                        .HasColumnName("Grup_Activo");

                    b.Property<string>("GrupDescripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Grup_Descripcion");

                    b.Property<DateTime>("GrupFechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("Grup_FechaCreacion");

                    b.Property<string>("GrupNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Grup_Nombre");

                    b.Property<string>("GrupRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Grup_Rol");

                    b.HasKey("GrupId");

                    b.HasIndex("GrupNombre")
                        .IsUnique();

                    b.ToTable("YarqtbGrupo", (string)null);
                });

            modelBuilder.Entity("Yarqua.Domain.Entities.YarqtbMetodoCC", b =>
                {
                    b.Property<int>("MetoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Meto_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MetoId"));

                    b.Property<bool>("MetoActivo")
                        .HasColumnType("bit")
                        .HasColumnName("Meto_Activo");

                    b.Property<string>("MetoDescripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Meto_Descripcion");

                    b.Property<DateTime>("MetoFechaActualizacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("Meto_FechaActualizacion");

                    b.Property<DateTime>("MetoFechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("Meto_FechaCreacion");

                    b.Property<string>("MetoNombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("Meto_Nombre");

                    b.HasKey("MetoId");

                    b.HasIndex("MetoNombre")
                        .IsUnique();

                    b.ToTable("YarqtbMetodoCC", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Yarqua.Domain.Entities.YarqtbPais", b =>
                {
                    b.Property<int>("PaisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Pais_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaisId"));

                    b.Property<int>("PaisEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2)
                        .HasColumnName("Pais_Estado");

                    b.Property<string>("PaisNombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Pais_Nombre");

                    b.HasKey("PaisId");

                    b.ToTable("YarqtbPais", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Yarqua.Domain.Entities.YarqtbRed", b =>
                {
                    b.Property<int>("RedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Red_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RedId"));

                    b.Property<int>("PaisId")
                        .HasColumnType("int")
                        .HasColumnName("Pais_Id");

                    b.Property<string>("RedNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Red_Nombre");

                    b.HasKey("RedId");

                    b.HasIndex("PaisId");

                    b.HasIndex("RedNombre")
                        .IsUnique();

                    b.ToTable("YarqtbRed", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Yarqua.Domain.Entities.YarqtbSensor", b =>
                {
                    b.Property<int>("SensId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Sens_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SensId"));

                    b.Property<int?>("CultId")
                        .HasColumnType("int")
                        .HasColumnName("Cult_Id");

                    b.Property<int>("RedId")
                        .HasColumnType("int")
                        .HasColumnName("Red_Id");

                    b.Property<bool>("SensActivo")
                        .HasColumnType("bit")
                        .HasColumnName("Sens_Activo");

                    b.Property<int>("SensCanales")
                        .HasColumnType("int")
                        .HasColumnName("Sens_Canales");

                    b.Property<string>("SensConectividad")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Sens_Conectividad");

                    b.Property<string>("SensEstado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Sens_Estado");

                    b.Property<DateTime>("SensFechaActualizacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("Sens_FechaActualizacion");

                    b.Property<DateTime>("SensFechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("Sens_FechaCreacion");

                    b.Property<string>("SensFinca")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Sens_Finca");

                    b.Property<decimal?>("SensLatitud")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("Sens_Latitud");

                    b.Property<decimal?>("SensLongitud")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("Sens_Longitud");

                    b.Property<string>("SensNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Sens_Nombre");

                    b.HasKey("SensId");

                    b.HasIndex("CultId");

                    b.HasIndex("RedId");

                    b.HasIndex("SensNombre")
                        .IsUnique();

                    b.ToTable("YarqtbSensor", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Yarqua.Domain.Entities.YarqtbUsuarioDispositivo", b =>
                {
                    b.Property<string>("UdiDeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("Udi_DeviceId");

                    b.Property<bool>("UdiActivo")
                        .HasColumnType("bit")
                        .HasColumnName("Udi_Activo");

                    b.Property<DateTime>("UdiFechaActualizacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("Udi_FechaActualizacion");

                    b.Property<DateTime>("UdiFechaRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("Udi_FechaRegistro");

                    b.Property<string>("UdiPlatform")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("Udi_Platform");

                    b.Property<string>("UsuaId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("Usua_Id");

                    b.HasKey("UdiDeviceId");

                    b.ToTable("YarqtbUsuarioDispositivo", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Yarqua.Domain.Entities.YarqtbUsuarioGrupo", b =>
                {
                    b.Property<string>("UsuaId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Usua_Id");

                    b.Property<int>("GrupId")
                        .HasColumnType("int")
                        .HasColumnName("Grup_Id");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UgrFechaAsignacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("Ugr_FechaAsignacion");

                    b.HasKey("UsuaId", "GrupId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("GrupId");

                    b.ToTable("YarqtbUsuarioGrupo", (string)null);
                });

            modelBuilder.Entity("Yarqua.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Usua_Id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("CiuId")
                        .HasColumnType("int")
                        .HasColumnName("Ciu_Id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("UsuaActivo")
                        .HasColumnType("bit")
                        .HasColumnName("Usua_Activo");

                    b.Property<DateTime>("UsuaFechaActualizacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("Usua_FechaActualizacion");

                    b.Property<DateTime>("UsuaFechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("Usua_FechaCreacion");

                    b.Property<DateTime>("UsuaFechaRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("Usua_FechaRegistro");

                    b.Property<string>("UsuaNombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Usua_Nombre");

                    b.HasKey("Id");

                    b.HasIndex("CiuId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("YarqtbUsuario", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Yarqua.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Yarqua.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Yarqua.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Yarqua.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Yarqua.Domain.Entities.YarqtbCiudad", b =>
                {
                    b.HasOne("Yarqua.Domain.Entities.YarqtbDepartamento", "Departamento")
                        .WithMany("Ciudades")
                        .HasForeignKey("DepoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("Yarqua.Domain.Entities.YarqtbDepartamento", b =>
                {
                    b.HasOne("Yarqua.Domain.Entities.YarqtbPais", "Pais")
                        .WithMany("Departamentos")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("Yarqua.Domain.Entities.YarqtbRed", b =>
                {
                    b.HasOne("Yarqua.Domain.Entities.YarqtbPais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("Yarqua.Domain.Entities.YarqtbSensor", b =>
                {
                    b.HasOne("Yarqua.Domain.Entities.YarqtbCultivo", "Cultivo")
                        .WithMany("Sensores")
                        .HasForeignKey("CultId");

                    b.HasOne("Yarqua.Domain.Entities.YarqtbRed", "Red")
                        .WithMany("Sensores")
                        .HasForeignKey("RedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cultivo");

                    b.Navigation("Red");
                });

            modelBuilder.Entity("Yarqua.Domain.Entities.YarqtbUsuarioGrupo", b =>
                {
                    b.HasOne("Yarqua.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany("Grupos")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("Yarqua.Domain.Entities.YarqtbGrupo", "Grupo")
                        .WithMany("Miembros")
                        .HasForeignKey("GrupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("Yarqua.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.HasOne("Yarqua.Domain.Entities.YarqtbCiudad", "Ciudad")
                        .WithMany()
                        .HasForeignKey("CiuId");

                    b.Navigation("Ciudad");
                });

            modelBuilder.Entity("Yarqua.Domain.Entities.YarqtbCultivo", b =>
                {
                    b.Navigation("Sensores");
                });

            modelBuilder.Entity("Yarqua.Domain.Entities.YarqtbDepartamento", b =>
                {
                    b.Navigation("Ciudades");
                });

            modelBuilder.Entity("Yarqua.Domain.Entities.YarqtbGrupo", b =>
                {
                    b.Navigation("Miembros");
                });

            modelBuilder.Entity("Yarqua.Domain.Entities.YarqtbPais", b =>
                {
                    b.Navigation("Departamentos");
                });

            modelBuilder.Entity("Yarqua.Domain.Entities.YarqtbRed", b =>
                {
                    b.Navigation("Sensores");
                });

            modelBuilder.Entity("Yarqua.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Navigation("Grupos");
                });
#pragma warning restore 612, 618
        }
    }
}
